creating form for new todos
mate-academy/react_add-todo-form pull request #1230
Opened 2022-11-07 12:57 UTC by 1stIndominus

[DEMO LINK](https://1stIndominus.github.io/react_add-todo-form/)

2022-11-07 15:45 UTC, qoa11a requested changes
![image](https://user-images.githubusercontent.com/102293862/200352686-38dfb1af-fc7e-412a-9ccc-dfed3e092824.png)
There's still error if I didn't select user first time and then have selected it.

2022-11-09 09:02 UTC, liliia-livandovskaya commented on src/App.tsx
> +  const [selectError, setSelectError] = useState(false);
```suggestion
  const [isSelectedValid, setSelectError] = useState(false);
```

2022-11-09 09:05 UTC, liliia-livandovskaya commented on src/App.tsx
> +              <option key={user.id} value={user.id}>{user.name}</option>
```suggestion
              <option key={user.id} value={user.id}>
                {user.name}
              </option>
```

2022-11-09 09:08 UTC, liliia-livandovskaya commented on src/App.tsx
> +    if (!title.trim().length) {
let's create a variable for` !title.trim().length` and use it there

2022-11-09 09:09 UTC, liliia-livandovskaya requested changes
Great job! Pay attention to the comments

2022-11-10 08:22 UTC, polosanya requested changes
Almost done! 
Please pay attention to my comments

2022-11-10 08:22 UTC, polosanya commented on src/App.tsx
> +  const [selectError, setSelectError] = useState(false);
![image](https://user-images.githubusercontent.com/96409563/201037948-89b426c3-e979-4b97-ae0a-d3351114aed5.png)
Try to rename your boolean variables according to this rule

2022-11-10 08:22 UTC, polosanya commented on src/App.tsx
> +  const titleTrim = title.trim().length;
You can create it inside handleSubmit function, as you don't use it anywhere else

2022-11-10 08:22 UTC, polosanya commented on src/App.tsx
> +            <span className="error">Plese choose a user</span>
```suggestion
            <span className="error">Please choose a user</span>
```
Probably that's the reason why you can't pass the test

2022-11-10 12:21 UTC, liliia-livandovskaya approved these changes
Great job 🔥

2023-12-06 14:41 UTC, closed without merging