solution
mate-academy/react_add-todo-form pull request #1238
Opened 2022-11-08 20:29 UTC by savchuksavchuk

[DEMO LINK](https://savchuksavchuk.github.io/react_add-todo-form/)

2022-11-09 09:36 UTC, liliia-livandovskaya commented on src/App.tsx
> +  const [toDoTitle, setTitle] = useState('');
```suggestion
  const [title, setTitle] = useState('');
```

2022-11-09 09:36 UTC, liliia-livandovskaya commented on src/App.tsx
> +  const [toDoUser, setUser] = useState('');
```suggestion
  const [user, setUser] = useState('');
```

2022-11-09 09:37 UTC, liliia-livandovskaya commented on src/App.tsx
> +              }}
this looks weak, instead, create a handler, and the same way all over your code

2022-11-09 09:38 UTC, liliia-livandovskaya commented on src/components/UserInfo/UserInfo.tsx
> +    <a className="UserInfo" href={`mailto:${user !== undefined ? user.email : ''}`}>
add formatting

2022-11-09 09:39 UTC, liliia-livandovskaya requested changes
GJ! Pay attention to the comments

2022-11-09 09:57 UTC, polosanya requested changes
Tests failed. Before making a Pull Request (or a new commit to an already existing PR), you need to write the `npm test` command in the terminal and make sure that all tests pass. After that, the mentor will be able to review the homework. If you have questions please ask them in fe_chat

2022-11-09 09:57 UTC, polosanya commented on src/App.tsx
> +  = 'abcdefghijkmnopqrstuvwxyzабвгґдеєжзиіїйклмнопрстуфхцчшщьюя123456789 ';
Do you really need to hardcore all the possible chars?
Try to find another solution

2022-11-09 09:57 UTC, polosanya commented on src/App.tsx
> +  const [toDos, addToDo] = useState([...todosFromServer]);
```suggestion
  const [todos, setTodos] = useState([...todosFromServer]);
```
Same below. Function name must be set according to the noun variable.
Please fix all cases

2022-11-09 09:57 UTC, polosanya commented on src/App.tsx
> +                const character = event.target.value.slice(-1);
Create separate functions to handle events

2022-11-09 09:57 UTC, polosanya commented on src/App.tsx
> +          {isTitleValid === -1 && (
What does -1 mean? Why can't you use boolean value?

2022-11-09 09:57 UTC, polosanya commented on src/App.tsx
> +              onChange={(event) => {
Separate function.
Please fix all cases

2022-11-19 22:14 UTC, savchuksavchuk commented
Hello, i can't manage with two last tests. I don't understand how they are running. Should i join one of the Q&A with this question?

2022-11-20 10:12 UTC, TarasHoliuk commented
> Hello, i can't manage with two last tests. I don't understand how they are running. Should i join one of the Q&A with this question?

It looks like it should work. I don't see the reason for another behavior. The code is good, so I'll approve.

2022-11-20 10:12 UTC, TarasHoliuk approved these changes

2024-12-28 10:48 UTC, closed without merging