Solution
mate-academy/react_add-todo-form pull request #1428
Opened 2023-02-02 22:30 UTC by vlad-boikov

[DEMO LINK](https://vlad-boikov.github.io/react_add-todo-form/)

2023-02-03 16:44 UTC, loralevitska requested changes
Good job! There are things that should be fixed:

2023-02-03 16:44 UTC, loralevitska commented on src/App.tsx
> +  const [noTitle, setNoTitle] = useState(false);
Rename [boolean variable](https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig)

2023-02-03 16:44 UTC, loralevitska commented on src/App.tsx
> +    }
Another option but it's up to you
```suggestion
    setNoUser(!user);
    setNoTitle(!title.trim());
```

2023-02-03 16:44 UTC, loralevitska commented on src/App.tsx
> +    ));
```suggestion
    setUpdatedTodos(currentToDo => ([
        ...currentToDo,
        newTodo,
      ]));
```

2023-02-03 16:44 UTC, loralevitska commented on src/App.tsx
> +    }
Use [`switch case`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch) in cases where you constantly compare one value with others

2023-02-03 16:44 UTC, loralevitska commented on src/App.tsx
> +            onChange={e => changeHandler(e)}
Fix it everywhere
```suggestion
            onChange={changeHandler}
```

2023-02-03 16:44 UTC, loralevitska commented on src/App.tsx
> +            style={{ marginRight: 5 }}
Better use classes for styles. Fix it everywhere

2023-02-03 16:44 UTC, loralevitska commented on src/components/TodoList/TodoList.tsx
> +    </section>
Use semantic tags for list `ul` `li`. Don't forget to remove default li dots

2023-02-04 13:59 UTC, SanyaBratashchuk approved these changes

2025-02-28 07:40 UTC, closed without merging