different components
mate-academy/react_add-todo-form pull request #1457
Opened 2023-02-07 07:23 UTC by Anton-Zhytonbaiev

2023-02-10 08:14 UTC, alexandra-protyanova commented
![Снимок экрана 2023-02-10 в 10 12 48](https://user-images.githubusercontent.com/102182808/218037767-b696403a-52cb-4e23-9ab5-4822364ea0e9.png)
There shouldn't be errors before I've started entering something

2023-02-10 08:16 UTC, alexandra-protyanova requested changes

2023-02-10 08:16 UTC, alexandra-protyanova commented on src/App.tsx
> +  const [todos, setTodos] = useState(preparedTodos);
set type to non primitive states

2023-02-10 08:16 UTC, alexandra-protyanova commented on src/components/TodoList/TodoList.tsx
> +  return (
avoid redundant `return`

2023-02-15 09:49 UTC, ArturErmolenko approved these changes

2024-01-05 09:10 UTC, closed without merging