Develop
mate-academy/react_add-todo-form pull request #1538
Opened 2023-03-21 14:24 UTC by Zelinskyi-Serhii

[DEMO LINK](https://Zelinskyi-Serhii.github.io/react_add-todo-form/)

2023-03-24 08:15 UTC, Yevhenii0536 approved these changes
gj!

2023-03-24 11:50 UTC, OleksiiBlezniuk requested changes
Let's add some styles to the page

2023-03-24 11:50 UTC, OleksiiBlezniuk commented on src/App.tsx
> +    }
```suggestion
    
    if (!userId) {
      setErrorUser(true);
      
      return;
    }

    if (!title.trim()) {
      setErrorTitle(true);
      
      return;
    }

    const newTodo = {
      id: findMax(todos),
      title,
      completed: false,
      userId,
      user: getUser(userId),
    };

    addTodos([...todos, newTodo]);
    reset();
```

2023-03-24 11:50 UTC, OleksiiBlezniuk commented on src/App.tsx
> +    }
Your first check - is code that will run if other checks will failed

2023-03-24 11:50 UTC, OleksiiBlezniuk commented on src/App.tsx
> +              }}
Let's create handler

2023-03-24 11:50 UTC, OleksiiBlezniuk commented on src/App.tsx
> +          {errorTitle && <span className="error">Please enter a title</span>}
```suggestion
          {errorTitle && (
            <span className="error">
              Please enter a title
            </span>
          )}
```

2023-03-24 11:50 UTC, OleksiiBlezniuk commented on src/App.tsx
> +              }}
Let's create handler

2023-04-03 15:55 UTC, OleksiiBlezniuk approved these changes
Great that you changed initial UI, good job 🔥 
I suggest it will be better to use lighter color for title or add some light stroke or shadow for text to make it more noticable on dark gradient

2023-04-03 15:55 UTC, OleksiiBlezniuk commented on src/App.tsx
> +    if (userId && title.trim()) {
I guess will be more logical to change this check a bit

2023-04-03 15:55 UTC, OleksiiBlezniuk commented on src/App.tsx
> +    if (userId && title.trim()) {
```suggestion
    if (!userId || !title) {
      setErrorUser(!userId);
      setErrorTitle(!title);
      
      return;
    }
    
```

2023-04-03 15:55 UTC, OleksiiBlezniuk commented on src/App.tsx
> +    addUserId(+event.target.value);
```suggestion
    addUserId(Number(event.target.value));
```

2023-07-12 19:52 UTC, closed without merging