solution
mate-academy/react_add-todo-form pull request #1558
Opened 2023-03-27 13:19 UTC by Nordexz

[DEMO LINK](https://nordexz.github.io/react_add-todo-form/)

2023-03-27 19:11 UTC, olecsiy-gavrilyuk requested changes
Gj , just a few comments

2023-03-27 19:11 UTC, olecsiy-gavrilyuk commented on src/App.tsx
> +}
set a type what a function return

2023-03-27 19:11 UTC, olecsiy-gavrilyuk commented on src/App.tsx
> +
choose , do you need User or not , if not delete comment

2023-03-27 19:11 UTC, olecsiy-gavrilyuk commented on src/App.tsx
> +}
the same  , what type of data this func return?

2023-03-27 19:11 UTC, olecsiy-gavrilyuk commented on src/App.tsx
> +        id: calculateId(todos),
newTodo

2023-04-02 13:05 UTC, Andr1yK requested changes

2023-04-02 13:05 UTC, Andr1yK commented on src/components/TodoInfo/TodoInfo.tsx
> +type Props = {
It's a good practice to use an interface for props in TypeScript. Replace `type Props` with `interface Props`.

2023-04-02 13:05 UTC, Andr1yK commented on src/components/TodoInfo/TodoInfo.tsx
> +  todo: Todo,
Add a semicolon at the end of the line to maintain consistent code style.

2023-04-02 13:05 UTC, Andr1yK commented on src/App.tsx
> +    setTitle(event.target.value);
Consider destructuring the `value` property from the `event.target` object for better readability: `const { value } = event.target;`

2023-04-02 13:05 UTC, Andr1yK commented on src/App.tsx
> +    setUserId(+event.target.value);
Consider destructuring the `value` property from the `event.target` object for better readability: `const { value } = event.target;`

2023-04-02 13:05 UTC, Andr1yK commented on src/App.tsx
> +function calculateId(todos: Todo[]): number {
Consider renaming the `calculateId` function to `generateNextId`/`getNextId` for better clarity on its purpose.

2023-04-02 13:05 UTC, Andr1yK commented on src/App.tsx
> +    }
DRY! 🫠

2023-04-02 13:05 UTC, Andr1yK commented on src/App.tsx
> +
```suggestion
      <TodoList todos={todos} />
```

2023-04-04 08:08 UTC, sergii-nosachenko requested changes
Fix Demo link - it doesn't work

2023-04-04 16:47 UTC, sergii-nosachenko approved these changes
Good, but the code can be improved.
Read comments.

2023-04-04 16:47 UTC, sergii-nosachenko commented on src/App.tsx
> +function findUser(id: number): User | null {
```suggestion
function findUserById(id: number): User | null {
```

2023-04-04 16:47 UTC, sergii-nosachenko commented on src/App.tsx
> +  const clear = () => {
```suggestion
  const clearForm = () => {
```

2023-04-04 16:47 UTC, sergii-nosachenko commented on src/App.tsx
> +    }
```suggestion
      const newTodo = {
        id: generateNextId(todos),
        title,
        completed: false,
        userId,
        user: findUser(userId),
      };

      setTodos(state => [...state, newTodo]);

      clearForm();
```

You don't need to check it twice

2023-04-04 16:47 UTC, sergii-nosachenko commented on src/App.tsx
> +            <select
```suggestion

            <select
```

2023-04-04 16:47 UTC, sergii-nosachenko commented on src/App.tsx
> +                return (
Useless `return`

2023-04-04 16:47 UTC, sergii-nosachenko commented on src/App.tsx
> +          {userError && (<span className="error">Please choose a user</span>)}
Split into rows

2023-04-04 16:47 UTC, sergii-nosachenko commented on src/components/TodoInfo/TodoInfo.tsx
> +        user && (
```suggestion
      {user && (
```

2023-04-04 16:47 UTC, sergii-nosachenko commented on src/components/TodoList/TodoList.tsx
> +  return (
Useless `return`

2023-04-04 16:49 UTC, sergii-nosachenko commented on src/App.tsx
> +    }
```suggestion
    if (!userId || !title) {
      setUserError(!userId);
      setTitleError(!title);
      
      return;
    }
```

2025-09-29 20:20 UTC, closed without merging