solution
mate-academy/react_add-todo-form pull request #1636
Opened 2023-04-25 17:17 UTC by Olekk17

[DEMO LINK](https://olekk17.github.io/react_add-todo-form/)

2023-04-25 17:47 UTC, closed without merging

2023-04-26 10:57 UTC, Vlad-Lischenovskiy approved these changes
Great Job!!!

2023-04-26 10:58 UTC, VenomMB approved these changes
GJ! Pay attention to comments.

2023-04-26 10:58 UTC, VenomMB commented on src/App.tsx
> +    if (!isUserNotChosen && !isTitleEmpty) {
It better move in a separate variable.

2023-04-26 10:58 UTC, VenomMB commented on src/App.tsx
> +          id: Math.max(...current.map(todo => todo.id)) + 1,
The same.

2023-04-26 10:58 UTC, VenomMB commented on src/App.tsx
> +    setIsTitleError(value.length === 0);
```suggestion
    setIsTitleError(!value.length);
```

2023-04-26 10:58 UTC, VenomMB commented on src/App.tsx
> +    const isUserNotChosen = selectedUser === null;
```suggestion
    const isTitleEmpty = !title.length;
    const isUserNotChosen = !selectedUser;
```

2023-04-26 14:37 UTC, SerhiiKirik approved these changes
Well done 🔥 
Your code is getting better every time, keep it up 🚀 
Let's fix bugs 🧑‍💻 
![image](https://user-images.githubusercontent.com/91411692/234608927-b5e4d37c-bfc5-4ee1-bc1f-b431a7c26358.png)

2023-04-26 14:37 UTC, SerhiiKirik commented on src/App.tsx
> +          )}
In all cases

2023-04-26 14:37 UTC, SerhiiKirik commented on src/App.tsx
> +    const isTitleEmpty = !title.length;
```suggestion
    event.preventDefault();
    
    const isTitleEmpty = !title.length;
```

2023-04-26 14:37 UTC, SerhiiKirik requested changes
Sync 🌍

2023-04-27 10:17 UTC, SerhiiKirik requested changes
Keep it up 🔥 
Let's fix this bug 🧑‍💻 
![image](https://user-images.githubusercontent.com/91411692/234833584-b4568f8f-7b78-4b05-aaa2-072d10ecd3a4.png)

2023-04-27 10:17 UTC, SerhiiKirik commented on src/App.tsx
> +
```suggestion
              </option>
              
              {usersFromServer.map((user) => (
```

2023-04-27 10:17 UTC, SerhiiKirik commented on src/App.tsx
> +          && (
in all cases
```suggestion
          {isUserError && (
```

2023-04-27 10:17 UTC, SerhiiKirik commented on src/App.tsx
> +    setIsUserError(isUserNotChosen);
if you found errors - return from function

2023-04-27 15:05 UTC, SerhiiKirik approved these changes
LGTM 🔥