reactTodoForm
mate-academy/react_add-todo-form pull request #1659
Opened 2023-04-26 19:00 UTC by ymys1

[DEMO LINK](https://ymys1.github.io/react_add-todo-form/)

2023-04-28 19:31 UTC, Anna-Kuzmenko commented on src/App.tsx
> +          <select
you should add lable 'User: ' to this select

2023-04-28 19:33 UTC, Anna-Kuzmenko commented on src/App.tsx
> +            handleAddButton();
this function should be in form (onSubmit)

2023-04-28 19:35 UTC, Anna-Kuzmenko requested changes
Good job! Move your onClick function to onSabmit in form and add labels

2023-05-09 09:38 UTC, SerhiiKirik requested changes
Well done 🔥 
Let's fix some bugs 🧑‍💻 
I can add todo just with spaces in the title
![image](https://user-images.githubusercontent.com/91411692/237055992-8cd32a63-fcea-4b1a-8d72-39e8af305b1e.png)

2023-05-09 09:38 UTC, SerhiiKirik commented on src/App.tsx
> +import { Todo, User, TodosWithUser } from './types/Types';
Add types to the PR
![image](https://user-images.githubusercontent.com/91411692/237056089-2acffba3-39ee-4d51-be06-eda139eac747.png)

2023-05-09 09:38 UTC, SerhiiKirik commented on src/App.tsx
> +  }
why do you need return here?
```suggestion
  function preparedTodosWithUsers(): TodosWithUser[] (
      todos.map(todo => ({
        ...todo,
        user: users.find(user => user.id === todo.userId) || null,
      )))
    );
  }
```

2023-05-09 09:38 UTC, SerhiiKirik commented on src/App.tsx
> +  const [todosWithUsers, setTodosWithUsers] = useState<TodosWithUser[]>(preparedTodosWithUsers());
Just wrap instead use eslint disable
```suggestion
  const [
   todosWithUsers,
   setTodosWithUsers
 ] = useState<TodosWithUser[]>(preparedTodosWithUsers());
```

2023-05-09 09:38 UTC, SerhiiKirik commented on src/App.tsx
> +    } else {
try to avoit `if / esle ` construction

2023-05-09 09:38 UTC, SerhiiKirik commented on src/App.tsx
> +      setAddValidated(true);
make a handle reset fucntion

2023-05-09 09:38 UTC, SerhiiKirik commented on src/App.tsx
> +            id: (todos.sort((a, b) => b.id - a.id)[0].id + 1),
split this with variables. Also, what is `a` & `b`?

2023-05-09 09:38 UTC, SerhiiKirik commented on src/App.tsx
> +            user: users.find(user => user.id === Number(selectedUser)) || null,
create a separate function for it & reuse

2023-05-09 09:38 UTC, SerhiiKirik commented on src/App.tsx
> +        onSubmit={(event) => (handleAddButton(event))}
it's the same
in all cases
```suggestion
        onSubmit={handleAddButton}
```

2023-05-09 09:38 UTC, SerhiiKirik commented on src/App.tsx
> +          )}
```suggestion
          <label htmlFor="titleInput">
          
            <input
              type="text"
              data-cy="titleInput"
              placeholder="Enter a title"
              value={currentTitle}
              onChange={event => setCurrentTitle(event.target.value)}
            />
          </label>
          
          {(!addValidated && !currentTitle) && (
            <span className="error">Please enter a title</span>
          )}
```

2023-05-09 09:38 UTC, SerhiiKirik commented on src/App.tsx
> +  const [addValidated, setAddValidated] = useState(true);
```suggestion
  const [isValid, setIsValid] = useState(true);
```

2023-05-09 09:38 UTC, SerhiiKirik commented on src/App.tsx
> +  const [addValidated, setAddValidated] = useState(true);
```suggestion
  const [isValid, setIsValid] = useState(true);
```

2023-05-09 09:38 UTC, SerhiiKirik commented on src/App.tsx
> +  const [addValidated, setAddValidated] = useState(true);
```suggestion
  const [isValid, setIsValid] = useState(true);
```

2023-05-10 08:44 UTC, ymys1 commented
Dont know why, but make new commit(
 I dont know if it'll be comfortable to review if I'll throw corrected file and code here, if not - I'll ask about it on QnA, just tell me)
 `import { useState } from 'react';
import './App.scss';
import usersFromServer from './api/users';
import todosFromServer from './api/todos';
import { TodoList } from './components/TodoList';
import { Todo, User, TodosWithUser } from './types/Types';

export const App = () => {
  const users: User[] = usersFromServer;
  const todos: Todo[] = todosFromServer;

  const preparedTodosWithUsers = () => (
    todos.map(todo => ({
      ...todo,
      user: users.find(user => user.id === todo.userId) || null,
    }))
  );

  const [selectedUser, setSelectedUser] = useState('');
  const [currentTitle, setCurrentTitle] = useState('');
  const [
    todosWithUsers,
    setTodosWithUsers,
  ] = useState<TodosWithUser[]>(preparedTodosWithUsers());
  const [isValid, setIsValid] = useState(true);

  const resetValidated = () => {
    setIsValid(true);
  };

  const resetSelectedUser = () => {
    setSelectedUser('');
  };

  const resetCrrentTitle = () => {
    setCurrentTitle('');
  };

  const validatedTitleAndUser = currentTitle && selectedUser;

  const handleAddButton = (event:React.FormEvent<HTMLInputElement>) => {
    if (validatedTitleAndUser) {
      event.preventDefault();
      setTodosWithUsers(
        [...todosWithUsers,
          {
            id: (todos.sort((a, b) => b.id - a.id)[0].id + 1),
            title: currentTitle,
            userId: Number(selectedUser),
            completed: false,
            user: users.find(user => user.id === Number(selectedUser)) || null,
          },
        ],
      );
      resetValidated();
      resetSelectedUser();
      resetCrrentTitle();
    }

    if (!validatedTitleAndUser) {
      setIsValid(false);
    }
  };

  return (
    <div className="App">
      <h1>Add todo form</h1>

      <form
        action="/api/users"
        method="POST"
        onSubmit={() => handleAddButton}
      >
        <div className="field">
          <label htmlFor="titleInput">

            <input
              type="text"
              data-cy="titleInput"
              placeholder="Enter a title"
              value={currentTitle}
              onChange={event => setCurrentTitle(event.target.value.trim())}
            />
          </label>

          {(!isValid && !currentTitle) && (
            <span className="error">Please enter a title</span>
          )}
        </div>

        <div className="field">
          <label htmlFor="userSelect">
            <select
              data-cy="userSelect"
              value={selectedUser}
              onChange={event => setSelectedUser(event.target.value)}
            >
              <option
                value=""
                selected
                disabled
              >
                Choose a user
              </option>

              {users.map(user => (
                <option
                  key={user.id}
                  value={user.id}
                >
                  {user.name}
                </option>
              ))}
            </select>
          </label>
          {(!isValid && !selectedUser) && (
            <span className="error">Please choose a user</span>
          )}
        </div>

        <button
          type="submit"
          data-cy="submitButton"
        >
          Add
        </button>
      </form>

      {todosWithUsers.map(todo => (
        <TodoList
          key={todo.id}
          todo={todo}
        />
      ))}
    </div>
  );
};
`
[App.tsx.txt](https://github.com/mate-academy/react_add-todo-form/files/11439838/App.tsx.txt)

2023-05-10 08:46 UTC, ymys1 commented
Txt file is at the end of message
Sorry for that

2023-05-11 10:55 UTC, SerhiiKirik requested changes
Go to the Q&A

2023-05-12 13:59 UTC, closed without merging