add task solution
mate-academy/react_add-todo-form pull request #1741
Opened 2023-06-06 09:14 UTC by NickMitchell61

[DEMO LINK](https://NickMitchell61.github.io/react_add-todo-form/)

Have the same failed tests in [react_static-list-of-todos](https://github.com/mate-academy/react_static-list-of-todos). 
All page tests passed, but TodoInfo - failed

https://mateacademy.slack.com/archives/C050SHYFFR9/p1685359229576659

2023-06-06 16:38 UTC, silchyn requested changes
Check behavior when the title consists of spaces

2023-06-06 16:38 UTC, silchyn commented on src/App.tsx
> +  const [titleErrorMessage, setTitleError] = useState(true);
```suggestion
  const [isTitleValid, setIsTitleValid] = useState(true);
```

2023-06-06 16:38 UTC, silchyn commented on src/components/TodoInfo/TodoInfo.tsx
> +    <article data-id={id} className={`TodoInfo ${completed ? 'TodoInfo--completed' : ''}`}>
use `cn`

2023-06-07 15:21 UTC, silchyn requested changes
> Check behavior when the title consists of spaces

2023-06-09 10:00 UTC, NickMitchell61 commented
@silchyn 

if I didn't fix the issue, could you explain the issues you see a little bit more?

2023-06-12 05:13 UTC, silchyn requested changes
Sure, basically, it is possible to submit the form with a title consisting of only spaces, which should not be possible

2023-06-20 09:24 UTC, silchyn requested changes

2023-06-20 09:24 UTC, silchyn commented on src/App.tsx
> +  const [isUserValid, setIsUserValid] = useState(true);
Is it valid initially?

2023-06-20 09:24 UTC, silchyn commented on src/App.tsx
> +  const handleOnSubmit = (event: React.FormEvent) => {
```suggestion
  const handleSubmit = (event: React.FormEvent) => {
```

2023-06-20 09:24 UTC, silchyn commented on src/App.tsx
> +}
You are finding user, not name

2023-06-20 09:24 UTC, silchyn commented on src/App.tsx
> +    const maxId = Math.max(...todos.map((todo) => todo.id));
```suggestion
    const id = Math.max(...todos.map((todo) => todo.id)) + 1;
```

2023-06-20 10:27 UTC, silchyn approved these changes

2023-06-20 10:27 UTC, silchyn commented on src/App.tsx
> +    const newUser = getUserByName(username);
Is it a new user?

2023-06-20 10:27 UTC, silchyn commented on src/App.tsx
> +  const foundName = usersFromServer.find(user => user.name === name);
Should it be `foundName`?

2023-07-05 08:03 UTC, closed without merging