Solution
mate-academy/react_add-todo-form pull request #1847
Opened 2023-07-17 20:28 UTC by outofs

https://outofs.github.io/react_add-todo-form/

2023-07-18 08:31 UTC, IraShtynda requested changes
Good start! Please fix comments, and it's better to extract styles from App.scss into separate files within the component folders.

2023-07-18 08:31 UTC, IraShtynda commented on src/App.tsx
> +          <input
Please add label, as in the working example

2023-07-18 08:31 UTC, IraShtynda commented on src/App.tsx
> +          <select
Please add label, as in the working example

2023-07-19 10:37 UTC, anstsot approved these changes
Good work, approving:sparkles:

2025-12-05 09:13 UTC, closed without merging