Solution
mate-academy/react_add-todo-form pull request #197
Opened 2020-07-06 05:52 UTC by V2473

[DEMO LINK](https://V2473.github.io/react_add-todo-form/)

2020-08-05 09:35 UTC, danheim requested changes

2020-08-05 09:35 UTC, danheim commented on src/api/todos.js
> +    userId: 2,
why

2020-08-05 09:35 UTC, danheim commented on src/components/NewTodo.js
> +  submit = (event) => {
```suggestion
  onSubmit = (event) => {
```

2020-08-05 09:35 UTC, danheim commented on src/components/NewTodo.js
> +        }}
эта логика не должна быть в этом теге, вынеси в функцию

2020-08-05 09:35 UTC, danheim commented on src/components/NewTodo.js
> +              && this.state.todo.userId !== 0) {
деструктурируй стейт

2020-08-05 09:35 UTC, danheim commented on src/components/NewTodo.js
> +                document.querySelector('#title').style.backgroundColor = 'red';
не используй такое в реакте, используй рефы
https://reactjs.org/docs/refs-and-the-dom.html

2020-08-05 09:35 UTC, danheim commented on src/components/NewTodo.js
> +              .style.removeProperty('background-color');
никакого querySelector`a в реакте быть не может

2020-08-05 09:35 UTC, danheim commented on src/components/NewTodo.js
> +              .querySelector('#users')
аналогично

2020-08-05 09:35 UTC, danheim commented on src/components/NewTodo.js
> +  todos: PropTypes.instanceOf(Array).isRequired,
некорректно типы описаны

2020-08-05 09:35 UTC, danheim commented on src/components/Todo.js
> +    return (
тут класс не нужен, как и стейт

2020-08-05 09:35 UTC, danheim commented on src/components/TodoLists.js
> +};
вынеси шейпы в константы

2020-08-11 11:04 UTC, Vladimir-Beliy commented on src/components/NewTodo.js
> +    this.usersRef = React.createRef();
в официальной документации есть описание когда нужно использывать реф, в остальных случаях мы используем стейт, нужно исправить

2020-08-11 11:04 UTC, Vladimir-Beliy commented on src/components/NewTodo.js
> +        });
это нужно отфармотировать, почему свойства объекта в одну строку???
поставь пустые строки где нужно, сделай диструктуризацию где нужно

2020-08-11 11:04 UTC, Vladimir-Beliy commented on src/components/Todo.js
> +      : `${props.title.slice(0, 37)}...`}
зачем это?
ограничить количество допустим символов в инпуте

2025-07-18 15:03 UTC, closed without merging