add solution
mate-academy/react_add-todo-form pull request #2022
Opened 2023-09-10 14:26 UTC by dimarogkov

[DEMO LINK](https://dimarogkov.github.io/react_add-todo-form/)

2023-09-11 06:15 UTC, etojeDenys requested changes
i can create the todo only with spaces, let's fix this case

2023-09-11 06:15 UTC, etojeDenys commented on src/components/TodoList/TodoList.tsx
> +  }[];
```suggestion
  todos: (Todo & {todoUser?: User})[];
```
we can simplify it

2023-09-11 06:15 UTC, etojeDenys commented on src/components/Form/Form.tsx
> +      onSubmit={(event) => submitForm(event)}
```suggestion
      onSubmit={submitForm}
```
we can simplify it

2023-09-11 09:50 UTC, VitaliyBondarenko1982 requested changes
Good job.
Needs some improvements.

2023-09-11 09:50 UTC, VitaliyBondarenko1982 commented on src/interfaces/todo.ts
> +  userId: number,
```suggestion
  userId: number,
  todoUser?: User,
```
and use this type everwhere

2023-09-11 09:50 UTC, VitaliyBondarenko1982 commented on src/App.tsx
> +  const finalTodos = createTodosArr(todosArr, usersFromServer);
better to make this function outside of component for initial todos state and after that change just state of todos.
in your implementation you make this operation during add each new todo

```
const getUserById = (userId: number) => {
  return usersFromServer.find(user => user && user.id === userId) || null;
};

const todosWithUser = todosFromServer
  .map(todo => ({ ...todo, todoUser: getUserById(todo.userId) }));
```

2023-09-11 09:50 UTC, VitaliyBondarenko1982 commented on src/App.tsx
> +  const [todosArr, setTodosArr] = useState<Todo[]>(todosFromServer);
```suggestion
  const [todosArr, setTodosArr] = useState<Todo[]>(todosWithUser);
```

2023-09-11 09:50 UTC, VitaliyBondarenko1982 commented on src/components/Form/Form.tsx
> +        userId,
```suggestion
      const newTodo: Todo = {
        id,
        title,
        completed: false,
        userId,
        todoUser: getUserById(userId)
```
and here you can add user immediately during make new todo

2023-09-12 17:48 UTC, etojeDenys requested changes
still can add the todo only with spaces
<img width="177" alt="image" src="https://github.com/mate-academy/react_add-todo-form/assets/70220667/fb0a42f7-03eb-4225-9f74-e9c45fefe40c">

2023-09-12 18:15 UTC, etojeDenys approved these changes
good job

2024-06-28 09:26 UTC, closed without merging