add task solution
mate-academy/react_add-todo-form pull request #2048
Opened 2023-09-13 13:51 UTC by Sergej161995

[DEMO LINK](https://Sergej161995.github.io/react_add-todo-form/)

2023-09-13 14:08 UTC, anastasiia-tilikina requested changes
very well done)

I have just couple suggestions to improve your code

2023-09-13 14:08 UTC, anastasiia-tilikina commented on src/App.tsx
> +    setHasUserError(userId === 0);
```suggestion
    setHasUserError(!!userId);
```

2023-09-13 14:08 UTC, anastasiia-tilikina commented on src/App.tsx
> +    if (trimmedTitle && userId > 0) {
```suggestion
    if (trimmedTitle && userId) {
```

2023-09-13 14:08 UTC, anastasiia-tilikina commented on src/components/TodoInfo/TodoInfo.tsx
> +    completed = false,
you don't need default value here since completed property always exists in todo

2023-09-13 14:08 UTC, anastasiia-tilikina commented on src/types/Todo.ts
> +  user?: User,
let's improve our types. since user after your map always exists in todo let's make it like this
```suggestion
  user: User || null,
```

2023-09-13 14:08 UTC, anastasiia-tilikina commented on src/App.tsx
> +  user: getUser(todo.userId),
```suggestion
  user: getUser(todo.userId) || null,
```

2023-09-14 14:19 UTC, mykhalenych requested changes
https://github.com/mate-academy/react_add-todo-form/assets/53228259/d0f05852-e826-4453-bcd0-5d34845b417f



<img width="569" alt="Screenshot 2023-09-14 at 17 19 37" src="https://github.com/mate-academy/react_add-todo-form/assets/53228259/a61a619b-acdc-438b-9daa-2e97e04a3218">

2023-09-14 17:42 UTC, closed without merging