Develop
mate-academy/react_add-todo-form pull request #2159
Opened 2023-11-03 03:12 UTC by HokageHEL

[DEMO LINK](https://HokageHEL.github.io/react_add-todo-form/)
I can't understand this test. This is Schrodinger's test - is passing and not passing at the same time.
Looking for your suggestions

2023-11-03 07:28 UTC, etojeDenys requested changes
i can create the todo only with spaces, let's fix that
<img width="231" alt="image" src="https://github.com/mate-academy/react_add-todo-form/assets/70220667/d8a00487-fa6d-4499-8fbd-76f764e28822">

2023-11-04 12:00 UTC, Esceype requested changes
At all great job!!!
Left some minor comments.

2023-11-04 12:00 UTC, Esceype commented on src/components/Services/User.ts
> +}
Why do you create Services inside components folder, is it a component?

2023-11-04 12:00 UTC, Esceype commented on src/components/TodoInfo/TodoInfo.tsx
> +      ${todo.completed && 'TodoInfo--completed'}`}
Use classNames lib please

2023-11-04 12:00 UTC, Esceype commented on src/components/UserInfo/UserInfo.tsx
> +);
```suggestion
export const UserInfo: React.FC<Props> = ({ user }) => {
  const { name, email } = user;

  return (
    <a className="UserInfo" href={`mailto:${email}`}>
      {name}
    </a>
  );
};```

2023-11-04 12:00 UTC, Esceype commented on src/components/TodoInfo/TodoInfo.tsx
> +    {todo.user && <UserInfo user={todo.user} />}
Destructure the todo in this component, since you're using more than one of its keys

2023-11-05 09:14 UTC, etojeDenys approved these changes
good job

2024-12-10 08:23 UTC, closed without merging