craeted todo-form
mate-academy/react_add-todo-form pull request #2182
Opened 2023-11-21 13:02 UTC by OPTIMISTIXX

https://OPTIMISTIXX.github.io/react_add-todo-form/

2023-11-21 13:19 UTC, nazarmatsevych requested changes
The code looks good,  add types and fix demo link pls

2023-11-21 13:19 UTC, nazarmatsevych commented on src/App.tsx
> +  const handleSubmit = (e) => {
```suggestion
  const handleSubmit = (e: React.FormEvent) => {
```
Add type here

2023-11-21 13:19 UTC, nazarmatsevych commented on src/App.tsx
> +  const handleTitleChange = (e) => {
```suggestion
  const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
```

And here

2023-11-21 13:19 UTC, nazarmatsevych commented on src/App.tsx
> +  const handlePersonChange = (e) => {
```suggestion
  const handlePersonChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
```

And here

2023-11-22 14:22 UTC, anastasiiavorobiova requested changes
Great work! 
<img width="416" alt="Screenshot 2023-11-22 at 16 14 02" src="https://github.com/mate-academy/react_add-todo-form/assets/135232001/01754139-856e-43dc-bb2a-439dc36d8567">
<img width="495" alt="Screenshot 2023-11-22 at 16 19 44" src="https://github.com/mate-academy/react_add-todo-form/assets/135232001/359bddae-492c-45e2-8fd0-16df08569391">
Error messages are showing before submitting. If the user enters spaces only, an error message is not shown, but the button is disabled. Consider enabling the submit button

2023-11-22 14:22 UTC, anastasiiavorobiova commented on src/App.tsx
> +    setTodos((prevTodos: any) => [...prevTodos, newTodo]);
Consider adding type here

2023-11-22 14:22 UTC, anastasiiavorobiova commented on src/components/TodoForm/TodoForm.tsx
> +  handleSubmit: (e: any) => void
Consider adding type here

2023-11-22 14:22 UTC, anastasiiavorobiova commented on src/components/TodoForm/TodoForm.tsx
> +  handlePersonChange: (e: any) => void
Consider adding type here

2023-11-22 14:22 UTC, anastasiiavorobiova commented on src/components/TodoForm/TodoForm.tsx
> +  handleTitleChange: (e: any) => void
Consider adding type here

2023-11-23 13:51 UTC, IvanFesenko requested changes
Not fixed
![2023-11-23_15h50_02](https://github.com/mate-academy/react_add-todo-form/assets/61904995/1aefcaf4-5ef6-4f6b-8be5-c42d94e9d50d)
![2023-11-23_15h49_34](https://github.com/mate-academy/react_add-todo-form/assets/61904995/fc9923ad-c96c-4ce8-9930-6a53cd9885f2)

2023-11-24 13:28 UTC, IvanFesenko approved these changes
well done

2025-08-04 16:12 UTC, closed without merging