solution
mate-academy/react_add-todo-form pull request #2254
Opened 2023-12-17 22:51 UTC by Timi2424

[DEMO LINK](https://Timi2424.github.io/react_add-todo-form/)

2023-12-18 11:57 UTC, jacekkosiba approved these changes

2023-12-18 15:29 UTC, mpiskadlo requested changes
Have you deployed your app properly? I get a 404 on your DEMO

2023-12-18 15:30 UTC, Timi2424 commented
> Have you deployed your app properly? I get a 404 on your DEMO

Ahhhh, same as always... Here, deployed

2023-12-19 07:25 UTC, mpiskadlo approved these changes
Great!

2024-07-05 16:36 UTC, closed without merging