solution
mate-academy/react_add-todo-form pull request #2421
Opened 2024-03-19 15:15 UTC by winniepuhh

[DEMO LINK](https://winniepuhh.github.io/react_add-todo-form/)

2024-03-19 19:39 UTC, Vlobdam reviewed
looks good 👍

2024-03-19 19:39 UTC, Vlobdam commented on src/App.tsx
> +export const prepearedPosts = todosFromServer.map(post => ({
typo
```suggestion
export const preparedPosts = todosFromServer.map(post => ({
```

2024-03-19 19:40 UTC, Vlobdam approved these changes

2024-03-21 14:02 UTC, StasSokolov1 requested changes
Almost done, let's improve your code a bit more

2024-03-24 19:37 UTC, BudnikOleksii requested changes
Good job 👍 
Just one moment should be fixed

2024-03-24 19:37 UTC, BudnikOleksii commented on src/components/UserInfo/UserInfo.tsx
> +  user: User | null;
```suggestion
  user: User;
```
user should be required, it doesn't make sense to render this component without user

2024-03-24 19:37 UTC, BudnikOleksii commented on src/components/UserInfo/UserInfo.tsx
> +
```suggestion
```

2024-03-25 10:48 UTC, BudnikOleksii approved these changes
Good work 👍

2024-03-28 09:28 UTC, closed without merging