solution
mate-academy/react_add-todo-form pull request #2514
Opened 2024-04-18 14:06 UTC by DanielLinker17

https://DanielLinker17.github.io/react_add-todo-form/

2024-04-18 14:22 UTC, anastasiiavorobiova requested changes
Great work! Almost done!

2024-04-19 05:47 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's make your code better

2024-04-19 05:47 UTC, volodymyr-soltys97 commented on src/App.tsx
> +  // #endregion
Remove comments everywhere
```suggestion
```

2024-04-19 05:47 UTC, volodymyr-soltys97 commented on src/App.tsx
> +          {todo.title.trim() === '' && showError && (
```suggestion
          {!todo.title.trim() && showError && (
```

2024-04-19 05:47 UTC, volodymyr-soltys97 commented on src/App.tsx
> +                {user.name}
Use destruction for `user`

2024-04-19 05:47 UTC, volodymyr-soltys97 commented on src/components/TodoInfo/TodoInfo.tsx
> +      <h2 className="TodoInfo__title">{todo.title}</h2>
Use destruction for `todo`

2024-04-19 05:47 UTC, volodymyr-soltys97 commented on src/components/UserInfo/UserInfo.tsx
> +      {user.name}
The same here

2024-04-19 11:19 UTC, anastasiiavorobiova approved these changes
Great work!

2025-07-29 00:38 UTC, closed without merging