done
mate-academy/react_add-todo-form pull request #261
Opened 2020-10-27 15:51 UTC by aionova

[DEMO LINK](https://aionova.github.io/react_add-todo-form/)

2020-10-28 07:04 UTC, yazheviks approved these changes
Вау! Классно)

2020-10-28 14:31 UTC, Vladimir-Beliy requested changes

2020-10-28 14:31 UTC, Vladimir-Beliy commented on src/App.js
> +    newTodoTitle: '',
этот стейт в форму

2020-10-28 14:31 UTC, Vladimir-Beliy commented on src/App.js
> +  }
это тоже в форму

2020-10-28 14:31 UTC, Vladimir-Beliy commented on src/components/Form/Form.jsx
> +      onClick={onAdd}
не клик а onSubmit на форму

2020-10-28 14:31 UTC, Vladimir-Beliy commented on src/components/Form/Form.jsx
> +  <form className="todo__form">
```suggestion
  <form  onSubmit={...} className="todo__form">
```

2020-10-28 14:31 UTC, Vladimir-Beliy commented on src/App.js
> +  }
```suggestion
  handleSelect = (event) => {
    this.setState({
      selected: event.target.value,
      errorHidden: true,
    });
  }

  handleTodoInput = (event) => {
    this.setState({
      newTodoTitle: event.target.value.replace(/[^\w ]+/, ''),
      errorHidden: true,
    });
  }
```
я думаю это лишнее)

2020-10-28 14:33 UTC, Vladimir-Beliy commented
передавай в app уже готовый объект с туду

2020-11-03 10:02 UTC, aliceblunt8 requested changes
fix this 

![image](https://user-images.githubusercontent.com/57598825/97971882-6631b680-1dcc-11eb-97b9-35d90d170185.png)

![image](https://user-images.githubusercontent.com/57598825/97971901-6d58c480-1dcc-11eb-86e4-265e3a851b73.png)

2020-11-03 10:02 UTC, aliceblunt8 commented on src/components/Form/Form.jsx
> +  }
too many if else statements, check for empty fields at the beginning of the function

2020-11-03 13:22 UTC, aliceblunt8 approved these changes

2023-09-27 08:13 UTC, closed without merging