add task solution
mate-academy/react_add-todo-form pull request #2656
Opened 2024-07-05 08:54 UTC by antonmolchanov18

2024-07-05 09:02 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code
Add the labels text to the inputs 
<img width="255" alt="image" src="https://github.com/mate-academy/react_add-todo-form/assets/64750958/ab9b0b1b-51cf-4d5d-b80f-aae766d26fe8">

2024-07-05 09:02 UTC, volodymyr-soltys97 commented on src/components/TodoInfo/TodoInfo.tsx
> +      <h2 className="TodoInfo__title">{todo.title}</h2>
Use destructuring for `todo`

2024-07-05 09:02 UTC, volodymyr-soltys97 commented on src/components/UserInfo/UserInfo.tsx
> +      {user.name}
Use destructuring for `user`

2024-07-06 08:46 UTC, etojeDenys requested changes

2024-07-06 08:46 UTC, etojeDenys commented on src/types/ToDoUser.ts
> +};
```suggestion
export type ToDoUser = {
  user: User | null;
  id: number;
  title: string;
  completed: boolean;
  userId: number;
};
```
just import the User type

2024-07-06 10:04 UTC, etojeDenys approved these changes
lgtm

2025-02-28 16:47 UTC, closed without merging