add todo form
mate-academy/react_add-todo-form pull request #2664
Opened 2024-07-13 09:54 UTC by Fetrw

[DEMO LINK](https://Fetrw.github.io/react_add-todo-form/)

2024-07-13 18:26 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's make your code better

2024-07-13 18:26 UTC, volodymyr-soltys97 commented on src/components/TodoInfo/TodoInfo.tsx
> +  const users = usersFromServer.find(user => user.id === todo.userId);
```suggestion
  const user = usersFromServer.find(user => user.id === todo.userId);
```

2024-07-13 18:26 UTC, volodymyr-soltys97 commented on src/components/TodoInfo/TodoInfo.tsx
> +      className={`TodoInfo ${todo.completed ? 'TodoInfo--completed' : ''}`}
Use the classnames library for add classes with condition

2024-07-14 08:31 UTC, anastasiiavorobiova requested changes
Great work! Consider fixing your tests 
<img width="1340" alt="Screenshot 2024-07-14 at 11 31 14" src="https://github.com/user-attachments/assets/6aad5d81-91ff-4414-81d1-c16c2c38e48c">

2024-07-14 09:00 UTC, anastasiiavorobiova approved these changes
Great work!

2024-07-14 09:00 UTC, anastasiiavorobiova commented on src/components/TodoList/TodoList.tsx
> +      <TodoInfo key={todo.id} todo={todo} users={users} />
```suggestion
      <TodoInfo key={todo.id} todo={todo} />
```

2026-01-16 17:46 UTC, closed without merging