react_add-todo-form
mate-academy/react_add-todo-form pull request #377
Opened 2021-03-24 21:06 UTC by SofiiaAsieieva

[DEMO LINK](https://SofiiaAsieieva.github.io/react_add-todo-form/)

2021-03-25 12:54 UTC, Jastler approved these changes

2021-03-25 14:28 UTC, solaryasha requested changes

2021-03-25 14:28 UTC, solaryasha commented on src/App.js
> +    isErrorBlock: {
```suggestion
    hasErrors: {
```

2021-03-25 14:28 UTC, solaryasha commented on src/App.js
> +          completed: ((Math.random() * 10) >= 5),
Що за магічний вираз ?

2021-03-26 09:11 UTC, solaryasha approved these changes

2026-02-02 20:02 UTC, closed without merging