Develop
mate-academy/react_add-todo-form pull request #378
Opened 2021-03-25 10:57 UTC by Jastler

[DEMO LINK](https://jastler.github.io/react_add-todo-form/)

2021-03-25 12:15 UTC, SofiiaAsieieva approved these changes
:fire:

2021-03-25 14:29 UTC, solaryasha requested changes
Коли я вибрав щось в селекті, чи написав в інпуті, то помилки мають зникати
<img width="410" alt="Screenshot 2021-03-25 at 16 29 25" src="https://user-images.githubusercontent.com/32794096/112489669-54ef4380-8d87-11eb-9b15-9914922a67d7.png">

2021-03-26 09:15 UTC, solaryasha requested changes

2021-03-26 09:15 UTC, solaryasha commented on src/App.js
> +    todo: preparedTodos,
В множині

2021-03-26 09:15 UTC, solaryasha commented on src/components/Todo.jsx
> +      <User {...user} />
Явно передавай пропси

2021-03-26 09:15 UTC, solaryasha commented on src/components/TodoList.jsx
> +            <Todo {...item} />
Явно передавай пропси

2021-03-26 09:15 UTC, solaryasha commented on src/App.js
> +        <TodoList list={todo} />
```suggestion
        <TodoList todos={todo} />
```

2021-03-26 09:15 UTC, solaryasha commented on src/components/TodoList.jsx
> +        {list.map(item => (
```suggestion
        {todos.map(todo => (
```

2021-03-26 09:15 UTC, solaryasha commented on src/components/TodosForm.jsx
> +    selectError: false,
Булеві змінні мають починатися з has, is, should, will

2021-03-26 09:15 UTC, solaryasha commented on src/components/TodosForm.jsx
> +        id: todo.length + 1,
Для генерування унікального id можеш використати https://www.npmjs.com/package/uuidv4
Тоді непотрібно буде передавати масив тудушок

2021-03-26 09:15 UTC, solaryasha commented on src/components/TodosForm.jsx
> +  handleSection = (event) => {
```suggestion
  handleSelection = (event) => {
```

2021-03-29 08:42 UTC, Vladimir-Beliy approved these changes
![image](https://user-images.githubusercontent.com/60401137/112810422-acd9c300-9083-11eb-8ff4-1ceb1a51977d.png)

2026-05-12 17:03 UTC, closed without merging