solved (will add styles tomorrow)
mate-academy/react_add-todo-form pull request #414
Opened 2021-04-11 21:05 UTC by JohnCrownHC

[DEMO LINK](https://JohnCrownHC.github.io/react_add-todo-form/)

2021-04-12 12:26 UTC, haiduk2019 approved these changes

2021-04-12 12:41 UTC, danheim requested changes
Good start

2021-04-12 12:41 UTC, danheim commented on src/App.js
> +const matchId = id => (
по названии функции не очень понятно что она делает
```suggestion
const findUserById = id => (
```

2021-04-12 12:41 UTC, danheim commented on src/App.js
> +        <TodoList todos={tasks} />
tasks todos tasks todos
рекомендую выбрать что-то одно

2021-04-12 12:41 UTC, danheim commented on src/components/Form/Form.jsx
> +import users from '../../api/users';
нельзя просто взять и заимпортить это в другом файле
это приходит с сервера один раз в компонент апп

2021-04-12 12:41 UTC, danheim commented on src/components/Form/Form.jsx
> +        <form onSubmit={this.handleSubmit}>
слишком большой отступ

2021-04-12 12:41 UTC, danheim commented on src/components/Form/Form.jsx
> +                  key={uuidv4()}
так нельзя делать
при каждом рендере здесь будет новое значение
в ключ нужно передавать что-то **постоянное** и уникальное

2021-04-12 12:41 UTC, danheim commented on src/components/Form/Form.jsx
> +            <div className="error">
тут не хватает отступа
проверь линтер, он такое бы не пропустил
https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

2021-04-12 12:41 UTC, danheim commented on src/components/TodoList/TodoList.jsx
> +        key={uuidv4()}
the same

2021-04-12 13:38 UTC, JohnCrownHC commented on src/App.js
> +        <TodoList todos={tasks} />
Изначально было todos, но тогда ругается линтер, мне самому было больно ставить tasks, но я уже исправил на другой вариант

2021-04-13 06:55 UTC, Denchepornyuk approved these changes

2021-04-13 08:42 UTC, Denchepornyuk approved these changes

2024-04-18 12:31 UTC, closed without merging