Develop
mate-academy/react_add-todo-form pull request #499
Opened 2021-07-28 11:31 UTC by vitaliy-martynyuk

[DEMO LINK](https://vitaliy-martynyuk.github.io/react_add-todo-form/)

2021-07-28 12:08 UTC, Viktor-Lepekha approved these changes

2021-07-29 12:21 UTC, solaryasha requested changes

2021-07-29 12:21 UTC, solaryasha commented on src/App.js
> +    userList: [...users],
https://mateacademy.slack.com/archives/C021CDS2J79/p1627561020157800

2021-07-29 12:21 UTC, solaryasha commented on src/App.js
> +      userId: +currentUser,
```suggestion
      userId: Number(currentUser),
```

2021-07-29 12:21 UTC, solaryasha commented on src/App.js
> +    currentUser: 0,
Це ж айдішка користувача, а не сам користувач

2021-07-29 12:21 UTC, solaryasha commented on src/App.js
> +            onClick={this.addTodo}
Ні, краще додати цей метод на onSubmit форми

2021-07-29 12:21 UTC, solaryasha commented on src/App.js
> +            {this.state.todoList.map(
Пропси теж можна деструктурувати

2021-07-29 12:21 UTC, solaryasha commented on src/App.js
> +                      ).name
Винеси в окремий метод

2021-07-29 12:21 UTC, solaryasha commented on src/App.js
> +              value=""
```suggestion
              value="0"
```

2021-07-29 13:41 UTC, solaryasha requested changes

2021-07-29 13:41 UTC, solaryasha commented on src/App.js
> +    todoList: [...todos],
```suggestion
    todos,
```

2021-07-29 13:41 UTC, solaryasha commented on src/App.js
> +            : <></>
```suggestion
          invalidTodo && <span>Specify correct todo</span>
```

2021-07-29 13:41 UTC, solaryasha commented on src/App.js
> +          }
Окремий метод

2021-07-29 13:41 UTC, solaryasha commented on src/App.js
> +        }
```suggestion
          invalidUser && <span>Choose user</span>
        }
```

2021-07-29 14:01 UTC, vitaliy-martynyuk commented on src/App.js
> +    todoList: [...todos],
буде помилка error  'todos' is already declared in the upper scope  no-shadow

2021-07-30 15:19 UTC, solaryasha approved these changes

2021-07-30 15:19 UTC, solaryasha commented on src/App.js
> +      return;
Краще показувати одразу дві помилки

2021-11-25 08:51 UTC, closed without merging