Solution?
mate-academy/react_add-todo-form pull request #529
Opened 2021-07-30 06:01 UTC by Vivdyuk

[DEMO LINK](https://vivdyuk.github.io/react_add-todo-form/)

2021-07-30 06:15 UTC, grynkiv0x001 approved these changes

2021-07-30 06:15 UTC, grynkiv0x001 commented on src/App.js
> +    user: users.find(human => human.id === todo.userId),
Нижче в коді ти називаєш змінну не human, a person. Як на мене це краще звучить, тому зміни і тут

2021-07-30 06:15 UTC, grynkiv0x001 commented on src/App.js
> +    initialTodos: preparedTodos,
Це ж не initialTodos, а взагалі всі тудушки, які в тебе. В тому числі і додані

2021-07-30 06:15 UTC, grynkiv0x001 commented on src/components/TodoList/TodoList.jsx
> +TodoList.propTypes = {
Я не впевнений, що наскільки ці пропси вже потрібні)

2021-07-30 07:20 UTC, danylo-onishchuk requested changes
ошибки должны одновременно появляться, если оба инпута пусты

2021-07-30 07:21 UTC, danylo-onishchuk requested changes

2021-07-30 07:21 UTC, danylo-onishchuk commented on src/App.js
> +  // eslint-disable-next-line consistent-return
delete it

2021-07-30 07:21 UTC, danylo-onishchuk commented on src/components/TodoList/TodoList.jsx
> +TodoList.propTypes = {
удали пропсы, которые ты не используешь в апке

2021-07-30 15:09 UTC, danylo-onishchuk requested changes
Без сабмита формы с пустыми инпутами не должны появляться ошибки

2021-08-02 09:51 UTC, solaryasha requested changes

2021-08-02 09:51 UTC, solaryasha commented on src/App.js
> +      [name]: value,
Якщо вже є помилка, то вона має зникати, коли ти щось нове друкуєш

2021-08-02 09:51 UTC, solaryasha commented on src/App.js
> +  onSubmit = (event) => {
```suggestion
  handleSubmit = (event) => {
```

2021-08-02 09:51 UTC, solaryasha commented on src/App.js
> +  onChange = (event) => {
```suggestion
  handleChange = (event) => {
```

2021-08-02 12:32 UTC, solaryasha approved these changes

2021-08-02 12:32 UTC, solaryasha commented on src/App.js
> +      [name === 'title' ? 'isTitleValid' : 'isUserValid']: true,
Не подобається мені цей хардкод, але окей

2021-08-02 12:34 UTC, Vivdyuk commented on src/App.js
> +      [name === 'title' ? 'isTitleValid' : 'isUserValid']: true,
Я цю штуку спочатку через світч робив, але вона мені здалась громіздкою

2023-02-13 12:02 UTC, closed without merging