Task was solved
mate-academy/react_add-todo-form pull request #642
Opened 2021-11-15 15:20 UTC by cyb1ove

[DEMO LINK](https://cyb1ove.github.io/react_add-todo-form/)

2021-11-16 12:51 UTC, podlesnyi-pavel requested changes
need to set default values after submit

2021-11-16 12:51 UTC, podlesnyi-pavel commented on src/components/TodoForm/TodoForm.tsx
> +  };
```
submitHandler = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const { onAdd } = this.props;

    this.checkError('title');
    this.checkError('user');

    if (this.state.title.value && this.state.user.value) {
      onAdd(this.state.title.value, this.state.user.value);
    }

		this.setState({
        title: {
      		value: '',
      		error: false,
    		},
        user: {
     		 value: 0,
      		error: false,
    		},
      });
  };
```

2021-11-22 10:13 UTC, solaryasha requested changes

2021-11-22 10:13 UTC, solaryasha commented on src/components/TodoForm/TodoForm.tsx
> +      error: false,
```suggestion
      hasValidationError: false,
```

2021-11-22 10:13 UTC, solaryasha commented on src/components/TodoForm/TodoForm.tsx
> +      error: false,
```suggestion
      hasValidationError: false,
```

2021-11-22 10:13 UTC, solaryasha commented on src/components/TodoForm/TodoForm.tsx
> +  changeTitleHandler = (e: ChangeEvent<HTMLInputElement>) => {
```suggestion
  changeTitleHandler = (event: ChangeEvent<HTMLInputElement>) => {
```

2021-11-22 10:13 UTC, solaryasha commented on src/components/TodoForm/TodoForm.tsx
> +  changeUserHandler = (e: ChangeEvent<HTMLSelectElement>) => {
```suggestion
  changeUserHandler = (event: ChangeEvent<HTMLSelectElement>) => {
```

2021-11-22 10:13 UTC, solaryasha commented on src/components/TodoForm/TodoForm.tsx
> +    this.setState({ user: { value: +e.target.value, error: false } });
```suggestion
    this.setState({ user: { value: Number(e.target.value), error: false } });
```

2021-11-22 10:13 UTC, solaryasha commented on src/components/TodoForm/TodoForm.tsx
> +  changeTitleHandler = (e: ChangeEvent<HTMLInputElement>) => {
It's better to name it properly, don't use `one letter` variable names

2021-11-22 10:13 UTC, solaryasha commented on src/components/TodoForm/TodoForm.tsx
> +            <option value="0" disabled>Chose a user</option>
```suggestion
            <option value="0" disabled>Choose a user</option>
```

2021-11-22 10:13 UTC, solaryasha commented on src/components/TodoList/TodoList.tsx
> +const nullUser: User = {
```suggestion
const userMock: User = {
```

2021-11-22 10:13 UTC, solaryasha commented on src/types/types.ts
> +export interface PreparedTodo extends Todo {
```suggestion
export interface TodoWithUser extends Todo {
```

2021-11-22 17:12 UTC, solaryasha approved these changes
Ще є невиправлені коментарі, але вони стосуються назв змінних. Це важливо - називати речі коректними іменами

2025-01-20 16:27 UTC, closed without merging