Develop
mate-academy/react_add-todo-form pull request #716
Opened 2022-01-22 15:45 UTC by E-Sharpilo

[DEMO LINK](https://E-Sharpilo.github.io/react_add-todo-form/)

2022-01-24 12:47 UTC, aliceblunt8 requested changes

2022-01-24 12:47 UTC, aliceblunt8 commented on src/App.tsx
> +            onClick={this.addTask}
add todo on submit action on the form

2022-01-24 12:47 UTC, aliceblunt8 commented on src/App.tsx
> +          users={this.state.users}
destructure everything from state

2022-01-24 12:47 UTC, aliceblunt8 commented on src/App.tsx
> +          onSubmit={e => (e.preventDefault())}
move e.preventDefault inside addTask

```suggestion
          onSubmit={this.addTask}
```

2022-01-24 12:47 UTC, aliceblunt8 commented on src/App.tsx
> +  Error = () => {
```suggestion
  showError = () => {
```

2022-01-25 13:46 UTC, danylo-onishchuk approved these changes

2024-12-28 14:45 UTC, closed without merging