Develop
mate-academy/react_add-todo-form pull request #720
Opened 2022-01-24 21:09 UTC by andrii-koptiev

[DEMO LINK](https://andrii-koptiev.github.io/react_add-todo-form/)

2022-01-26 15:58 UTC, Oleksandr-Leshchenko requested changes

2022-01-26 15:58 UTC, Oleksandr-Leshchenko commented on src/App.tsx
> +  };
Это плохая идея - создавать по методу для каждого изменяемого поля. А если таких полей будет 20? 100?
Надо все прописать через один метод

2022-01-26 22:47 UTC, andrii-koptiev commented on src/App.tsx
> +  };
Спасибо за замечение. Заодно еще в некоторых моментах улучшил код

2022-01-27 02:21 UTC, Oleksandr-Leshchenko approved these changes

2022-01-28 09:16 UTC, danheim approved these changes

2022-01-28 09:16 UTC, danheim commented on src/App.tsx
> +  currTodos: Todo[];
```suggestion
  todos: Todo[];
```

2023-09-26 21:08 UTC, closed without merging