solution
mate-academy/react_add-todo-form pull request #791
Opened 2022-03-24 12:32 UTC by SanyaBratashchuk

[DEMO LINK](https://SanyaBratashchuk.github.io/react_add-todo-form/)

2022-03-25 11:17 UTC, Andr1yK requested changes
Все зроблено добре, проте є пару моментів, які краще виправити

_Також можна було б не показувати помилок після додавання таски))_

2022-03-25 11:17 UTC, Andr1yK commented on src/helpers/validation.tsx
> +};
Так як тут ти не використовуєш jsx, то можн було назвати протсо validation.ts

2022-03-25 11:17 UTC, Andr1yK commented on src/App.tsx
> +        }}
Краще винеси це в окрему функцію

2022-03-25 11:17 UTC, Andr1yK commented on src/App.tsx
> +            }}
тут теж можна було б винести

2022-03-25 11:17 UTC, Andr1yK commented on src/components/TodoList.tsx
> +      ))}
додай атрибут key

2022-03-25 17:28 UTC, Andr1yK approved these changes
LGTM🔥

2022-03-25 17:28 UTC, Andr1yK commented on src/App.tsx
> +              titleOnChangeHandler(event);
onChange={(event) => {  titleOnChangeHandler(event);}}
те ж саме
onChange={titleOnChangeHandler}

2022-03-28 14:02 UTC, solaryasha requested changes

2022-03-29 14:36 UTC, solaryasha approved these changes

2026-05-02 10:22 UTC, closed without merging