add files
mate-academy/react_add-todo-form pull request #840
Opened 2022-05-15 21:40 UTC by misha200119

[DEMO LINK] (https://misha200119.github.io/react_add-todo-form/)

2022-05-18 07:47 UTC, yaremenko-maksym reviewed
All good!

2022-05-18 08:14 UTC, MaksimusCRS requested changes

2022-05-18 08:14 UTC, MaksimusCRS commented on src/App.scss
> +    margin: 0 0 50px !important;
Зачем тебе тут !important?

2022-05-18 08:14 UTC, MaksimusCRS commented on src/components/UserInfo/UserInfo.tsx
> +  user?: User;
```suggestion
  user: User;
```

2022-05-18 08:14 UTC, MaksimusCRS commented on src/components/ToDoInfo/ToDoInfo.tsx
> +      <UserInfo user={user} />
Рендерь этот компонент только если у тебя есть юзер

2022-05-18 08:14 UTC, MaksimusCRS commented on src/components/UserInfo/UserInfo.tsx
> +};
Не миксуй с ts

2022-05-19 11:11 UTC, MaksimusCRS approved these changes

2025-08-10 12:48 UTC, closed without merging