solution
mate-academy/react_add-todo-form pull request #884
Opened 2022-06-08 10:06 UTC by yelnikov-andrii

[DEMO LINK](https://yelnikov-andrii.github.io/react_add-todo-form/)

2022-06-08 17:19 UTC, RomekIvantsiv commented on src/App.tsx
> +            </select>
add an empty option `Choose a user` to the users select

2022-06-09 10:36 UTC, Denchepornyuk requested changes
<img width="398" alt="Screenshot 2022-06-09 at 13 28 34" src="https://user-images.githubusercontent.com/37452763/172826610-8b10222e-fe88-4d21-af57-20045026dfc7.png">

clear user in select after submitting the form

2022-06-09 10:36 UTC, Denchepornyuk commented on src/App.tsx
> +  const [createdId, setCreatedId] = useState(0);
you don't need createdId, you can remove it

2022-06-09 10:36 UTC, Denchepornyuk commented on src/App.tsx
> +        id: createdId,
```suggestion
      const createdUser = {
        title: inputedTitle,
        id: preparedUsers.length + 1,
```

2022-06-09 10:36 UTC, Denchepornyuk commented on src/App.tsx
> +              }}
```suggestion
              onClick={addUser}
```

2022-06-10 09:51 UTC, Denchepornyuk approved these changes

2024-03-19 15:10 UTC, closed without merging