solution
mate-academy/react_add-todo-form pull request #887
Opened 2022-06-08 20:30 UTC by lytvyshko

- [DEMO LINK](https://lytvyshko.github.io/react_add-todo-form/)

2022-06-12 06:17 UTC, khozhainov-aleksandr approved these changes
Good job 🔥

2022-06-13 13:12 UTC, Anna-Tkachenko requested changes

2022-06-13 13:12 UTC, Anna-Tkachenko commented on src/App.tsx
> +        completed: false,
You should add checkbox in the form that should be responsible for this field

2022-06-14 11:49 UTC, Anna-Tkachenko approved these changes
Good job!

2024-09-16 10:16 UTC, closed without merging