Done
mate-academy/react_add-todo-form pull request #915
Opened 2022-06-16 13:04 UTC by Virass

[DEMO LINK](https://Virass.github.io/react_add-todo-form/)

2022-06-17 14:35 UTC, Bohdan-Maksymiuk requested changes

2022-06-17 14:35 UTC, Bohdan-Maksymiuk commented on src/App.tsx
> +        id: preparedTodoList.length + 1,
> id is a maximal id in the array + 1

2022-06-17 15:31 UTC, Virass commented on src/App.tsx
> +        id: preparedTodoList.length + 1,
Agree. Fix complete.

2022-06-21 08:58 UTC, ArturErmolenko approved these changes

2026-03-02 19:46 UTC, closed without merging