1
mate-academy/react_add-todo-form pull request #997
Opened 2022-07-22 20:49 UTC by MAIK-01

[DEMO LINK](https://MAIK-01.github.io/react_add-todo-form/)

2022-07-26 10:58 UTC, alexandra-protyanova requested changes
Add rest of files, and completed to todo info

2022-07-26 10:58 UTC, alexandra-protyanova commented on src/App.tsx
> +        <div className={inputError ? 'input__error' : ''}>
u can use classnames library

2022-07-28 13:58 UTC, ArtemTopolskyi approved these changes

2022-07-28 13:58 UTC, ArtemTopolskyi commented on src/App.tsx
> +  const handlerSubmit = (event: { preventDefault: () => void; }) => {
```suggestion
  const handlerSubmit = (event: { preventDefault: () => void; }) => {
```
use provided react type

2022-07-28 13:58 UTC, ArtemTopolskyi commented on src/components/TodoList/TodoList.tsx
> +  const vsbTodos = todos
what means this variable name

2023-03-27 20:44 UTC, closed without merging